/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-page': 'var(--bg-page)',
        'bg-surface': 'var(--bg-surface)',
        'bg-hover': 'var(--bg-hover)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-subtle': 'var(--accent-subtle)',
        'accent-border': 'var(--accent-border)',
        danger: 'var(--danger)',
        'danger-bg': 'var(--danger-bg)',
        warning: 'var(--warning)',
        'warning-bg': 'var(--warning-bg)',
        success: 'var(--success)',
        'success-bg': 'var(--success-bg)',
        neutral: 'var(--neutral)',
        'neutral-bg': 'var(--neutral-bg)',
        'card-rose': 'var(--card-rose)',
        'card-sand': 'var(--card-sand)',
        'card-mist': 'var(--card-mist)',
        'sidebar-bg': 'var(--sidebar-bg)',
        'sidebar-icon': 'var(--sidebar-icon)',
        'sidebar-icon-active': 'var(--sidebar-icon-active)',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.07), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.10), 0 2px 4px rgba(0,0,0,0.06)',
        'panel': '0 8px 24px rgba(0,0,0,0.12), 0 2px 6px rgba(0,0,0,0.06)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
